### ISSUE TITLE
MarkerDetector arguments

### ISSUE THREAD

**Issue by AndreasAZiegler** [fehlfarbe/python-aruco#1]
I try to detect a single marker. I created `markerdetector = aruco.MarkerDetector()` and try to detect with `marker = markerdetector.detect(frame, camaraparam, 200)` but this gives me the error message:
`if marker.isValid(): AttributeError: 'tuple' object has no attribute 'isValid'"`

 If I run `markerdetector.detect(frame, marker, camparam)`, I get the following error message
`File "/usr/lib/python3.5/site-packages/aruco.py", line 679, in detect
    return _aruco.MarkerDetector_detect(self, *args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'MarkerDetector_detect'.`

How do I have to use markerdetector the right was? Is there a problem with the parameters in the python wrapper?

Thank you in advance.

Cheers, Andreas

**Comment by fehlfarbe** [comment]
Hi Andreas,

You get an AttributeError because `markerdetector.detect()` returns a list with detected markers. You can iterate through your list like this:

``` python
markers = markerdetector.detect(frame, camaraparam, 200)
for m in markers:
    print "detected marker #%d, valid? %s" % (m.id, m.isValid())
```

Edit:
`markerdetector.detect(frame, marker, camparam)` doesn't work because it's overwritten in `aruco.i`. It returns a std::vectoraruco::Marker that is converted to a Python list.

**Comment by AndreasAZiegler** [comment]
Hi fehlfarbe

Thanks a lot for your help. It is indeed working.

Cheers, Andreas

**Comment by fehlfarbe** [comment]
Perfect :)
